nome_cliente = input("informe seu nome: ")
idade = input("por favor, informe sua idade: ")
print("e agora, seu endereço, por gentileza: ")
rua = input("Rua: ")
bairro = input("Bairro: ")
cidade = input("cidade: ")
profissao = input ("e por ultimo, sua profissão: ")
print("Boas vindas ", nome_cliente, "!")
print("aqui esta suas informações: sua idade:", idade,"anos, seu endereço:", rua,",",bairro,",", cidade,", e sua profissao:", profissao,)